# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

workspace 'AMQP Client Sample WS'

target 'AMQP Client Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AMQP Client Sample
  pod 'AzureIoTUtility'
  #pod 'AzureIoTuMqtt'
  pod 'AzureIoTuAmqp'
  pod 'AzureIoTHubClient'
end
