# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

workspace 'AMQPWS Client Sample WS'

target 'AMQPWS Client Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AMQPWS Client Sample
  pod 'AzureIoTUtility'
  #pod 'AzureIoTuMqtt'
  pod 'AzureIoTuAmqp'
  pod 'AzureIoTHubClient', '1.0.0-pre-release-1.0.8'
end
