# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

workspace 'File Upload Sample WS'

target 'File Upload Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for File Upload Sample
  pod 'AzureIoTUtility'
  #pod 'AzureIoTuMqtt'
  pod 'AzureIoTuAmqp'
  pod 'AzureIoTHubClient'
end
